"""Add subscriptions and referral_rewards tables

Revision ID: 1ad12df6ab1e
Revises: b456f1b1c460
Create Date: 2025-11-24 18:28:24.350016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad12df6ab1e'
down_revision: Union[str, Sequence[str], None] = 'b456f1b1c460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Создаем enum типы если они не существуют
    from sqlalchemy import text
    conn = op.get_bind()

    # Проверяем существование таблиц перед созданием (делаем это ПЕРВЫМ)
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    # Проверяем и создаем ReferralRewardStatus
    try:
        result = conn.execute(text(
            "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'referralrewardstatus')"
        ))
        if not result.scalar():
            sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='referralrewardstatus').create(conn)
    except Exception as e:
        print(f"Warning: Could not create ReferralRewardStatus enum: {e}")

    # Проверяем и создаем SubscriptionType
    try:
        result = conn.execute(text(
            "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'subscriptiontype')"
        ))
        if not result.scalar():
            sa.Enum('MONTHLY_100', 'DAILY_20', 'UNLIMITED', 'CUSTOM', name='subscriptiontype').create(conn)
    except Exception as e:
        print(f"Warning: Could not create SubscriptionType enum: {e}")

    # Проверяем и создаем ServiceType
    try:
        result = conn.execute(text(
            "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'servicetype')"
        ))
        if not result.scalar():
            sa.Enum('ENVATO', 'FREEPIK', 'ALL', name='servicetype').create(conn)
    except Exception as e:
        print(f"Warning: Could not create ServiceType enum: {e}")

    # ### commands auto generated by Alembic - please adjust! ###
    if 'referral_rewards' not in existing_tables:
        op.create_table('referral_rewards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=False),
    sa.Column('referred_id', sa.BigInteger(), nullable=False),
    sa.Column('reward_type', sa.String(), nullable=False),
    sa.Column('reward_value', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='referralrewardstatus'), nullable=True),
    sa.Column('condition_met', sa.Boolean(), nullable=True),
    sa.Column('condition_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('rewarded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    if 'subscriptions' not in existing_tables:
        op.create_table('subscriptions',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('subscription_type', sa.Enum('MONTHLY_100', 'DAILY_20', 'UNLIMITED', 'CUSTOM', name='subscriptiontype'), nullable=False),
        sa.Column('service_type', sa.Enum('ENVATO', 'FREEPIK', 'ALL', name='servicetype'), nullable=True),
        sa.Column('total_limit', sa.Integer(), nullable=True),
        sa.Column('daily_limit', sa.Integer(), nullable=True),
        sa.Column('used_total', sa.Integer(), nullable=True),
        sa.Column('used_today', sa.Integer(), nullable=True),
        sa.Column('last_reset_date', sa.Date(), nullable=True),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('end_date', sa.DateTime(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('payment_id', sa.BigInteger(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    # Проверяем существование колонок в downloads
    downloads_columns = [col['name'] for col in inspector.get_columns('downloads')]
    if 'subscription_id' not in downloads_columns:
        op.add_column('downloads', sa.Column('subscription_id', sa.BigInteger(), nullable=True))
    if 'service_type' not in downloads_columns:
        op.add_column('downloads', sa.Column('service_type', sa.Enum('ENVATO', 'FREEPIK', 'ALL', name='servicetype'), nullable=True))

    # Проверяем constraint перед созданием
    try:
        op.create_foreign_key(None, 'downloads', 'subscriptions', ['subscription_id'], ['id'])
    except:
        pass  # Constraint уже существует

    # ВАЖНО: Проверяем колонки в users ДО попытки удалить constraint
    user_columns = [col['name'] for col in inspector.get_columns('users')]

    # Проверяем существование constraint и column перед удалением
    if 'referred_by_id' in user_columns:
        try:
            op.drop_constraint('users_referred_by_id_fkey', 'users', type_='foreignkey')
        except Exception as e:
            # Constraint может не существовать или уже удален
            print(f"Warning: Could not drop constraint: {e}")
            pass

        try:
            op.drop_column('users', 'referred_by_id')
        except Exception as e:
            # Колонка может уже быть удалена
            print(f"Warning: Could not drop column: {e}")
            pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referred_by_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_referred_by_id_fkey', 'users', 'users', ['referred_by_id'], ['id'])
    op.drop_constraint(None, 'downloads', type_='foreignkey')
    op.drop_column('downloads', 'service_type')
    op.drop_column('downloads', 'subscription_id')
    op.drop_table('subscriptions')
    op.drop_table('referral_rewards')
    # ### end Alembic commands ###
