"""Remove old subscription fields from users

Revision ID: 539e55ed7fe1
Revises: 1ad12df6ab1e
Create Date: 2025-11-24 23:30:08.883330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '539e55ed7fe1'
down_revision: Union[str, Sequence[str], None] = '1ad12df6ab1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    user_columns = [col['name'] for col in inspector.get_columns('users')]

    # Удаляем колонки только если они существуют
    if 'is_subscribed' in user_columns:
        try:
            op.drop_column('users', 'is_subscribed')
        except Exception as e:
            print(f"Warning: Could not drop is_subscribed: {e}")

    if 'subscription_until' in user_columns:
        try:
            op.drop_column('users', 'subscription_until')
        except Exception as e:
            print(f"Warning: Could not drop subscription_until: {e}")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_subscribed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
