"""Remove old subscription fields from users

Revision ID: 539e55ed7fe1
Revises: 1ad12df6ab1e
Create Date: 2025-11-24 23:30:08.883330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '539e55ed7fe1'
down_revision: Union[str, Sequence[str], None] = '1ad12df6ab1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_subscribed')
    op.drop_column('users', 'subscription_until')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_subscribed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
