"""add ai_credits to users table

Revision ID: cfc529f762df
Revises: 42d1a229ebd0
Create Date: 2025-12-26 17:02:08.689389

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfc529f762df"
down_revision: Union[str, Sequence[str], None] = "42d1a229ebd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("ai_credits", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "users", sa.Column("ai_credits_used", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "ai_credits_used")
    op.drop_column("users", "ai_credits")
    # ### end Alembic commands ###
